RecipeFormatVersion: '2020-01-25'
ComponentName: com.example.awsggpi4
ComponentVersion: '1.0.8'
ComponentType: aws.greengrass.generic
ComponentDescription: YOLO object detection on Raspberry Pi 4 - person/vehicle counting, MJPEG stream, daily CSV logging, S3 upload.
ComponentPublisher: awsggpi4

ComponentConfiguration:
  DefaultConfiguration:
    USE_PICAMERA: '1'
    RTSP_URL: 'rtsp://user:password@192.168.88.44:554/cam/realmonitor?channel=1&subtype=0'
    FRAME_WIDTH: '1280'
    FRAME_HEIGHT: '720'
    ROI1: '0,0,640,720'
    ROI2: '640,0,1280,720'
    YOLO_MODEL_PATH: ''
    STREAM_PORT: '9090'
    INFER_IMG_SIZE: '640'
    INFER_EVERY_N: '1'
    COUNT_CLASS_IDS: '0,1,3'
    DRAW_DETECTIONS: '1'
    TRACK_IOU_THRESHOLD: '0.3'
    TRACK_MAX_AGE_SECONDS: '5'
    COUNT_INTERVAL_MINUTES: '1'
    TZ_OFFSET_MINUTES: '330'
    HOURLY_CSV_PATH: ''
    ROI_CONFIG_PATH: ''
    LOG_DIR: ''
    ENABLE_IMSHOW: '0'
    JPEG_QUALITY: '85'
    S3_BUCKET: 'lassi-shop-iot'
    S3_PREFIX: 'detections/'
    AWS_REGION: 'ap-south-1'

Manifests:
  - Platform:
      os: linux
      architecture: aarch64
    Artifacts:
      - Uri: 's3://lassi-shop-iot/components/awsggpi4/awsggpi4.zip'
        Unarchive: ZIP
        Permission:
          Read: ALL
          Execute: NONE
    Lifecycle:
      install:
        Script: |
          set -e
          apt-get update
          apt-get install -y python3-pip python3-venv python3-libcamera python3-picamera2 libcap-dev \
            build-essential libglib2.0-0 libsm6 libxrender1 libxext6 \
            libjpeg-dev libpng-dev curl
          python3 -m venv --system-site-packages {work:path}/venv
          {work:path}/venv/bin/pip install --upgrade pip setuptools wheel
          {work:path}/venv/bin/pip install -r {artifacts:decompressedPath}/awsggpi4/awsggpi4/requirements.txt
          mkdir -p {work:path}/models
          cp -n {artifacts:decompressedPath}/awsggpi4/awsggpi4/roi_config.json.example {work:path}/roi_config.json || true
          if [ ! -f {work:path}/models/yolov8n.pt ]; then
            (curl -sSL -o {work:path}/models/yolov8n.pt "https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt" || \
             wget -q -O {work:path}/models/yolov8n.pt "https://github.com/ultralytics/assets/releases/download/v8.2.0/yolov8n.pt") || true
          fi
        RequiresPrivilege: true
        Timeout: 600
      run:
        Script: |
          export USE_PICAMERA="{configuration:/USE_PICAMERA}"
          export RTSP_URL="{configuration:/RTSP_URL}"
          export FRAME_WIDTH="{configuration:/FRAME_WIDTH}"
          export FRAME_HEIGHT="{configuration:/FRAME_HEIGHT}"
          export ROI1="{configuration:/ROI1}"
          export ROI2="{configuration:/ROI2}"
          export STREAM_PORT="{configuration:/STREAM_PORT}"
          export INFER_IMG_SIZE="{configuration:/INFER_IMG_SIZE}"
          export INFER_EVERY_N="{configuration:/INFER_EVERY_N}"
          export COUNT_CLASS_IDS="{configuration:/COUNT_CLASS_IDS}"
          export DRAW_DETECTIONS="{configuration:/DRAW_DETECTIONS}"
          export TRACK_IOU_THRESHOLD="{configuration:/TRACK_IOU_THRESHOLD}"
          export TRACK_MAX_AGE_SECONDS="{configuration:/TRACK_MAX_AGE_SECONDS}"
          export COUNT_INTERVAL_MINUTES="{configuration:/COUNT_INTERVAL_MINUTES}"
          export TZ_OFFSET_MINUTES="{configuration:/TZ_OFFSET_MINUTES}"
          export ENABLE_IMSHOW="{configuration:/ENABLE_IMSHOW}"
          export JPEG_QUALITY="{configuration:/JPEG_QUALITY}"
          export YOLO_MODEL_PATH="{configuration:/YOLO_MODEL_PATH}"
          export HOURLY_CSV_PATH="{configuration:/HOURLY_CSV_PATH}"
          export ROI_CONFIG_PATH="{configuration:/ROI_CONFIG_PATH}"
          export LOG_DIR="{configuration:/LOG_DIR}"
          export S3_BUCKET="{configuration:/S3_BUCKET}"
          export S3_PREFIX="{configuration:/S3_PREFIX}"
          export AWS_REGION="{configuration:/AWS_REGION}"
          [ -z "$YOLO_MODEL_PATH" ] && export YOLO_MODEL_PATH="{work:path}/models/yolov8n.pt"
          [ -z "$HOURLY_CSV_PATH" ] && export HOURLY_CSV_PATH="{work:path}/detections.csv"
          [ -z "$ROI_CONFIG_PATH" ] && export ROI_CONFIG_PATH="{work:path}/roi_config.json"
          [ -z "$LOG_DIR" ] && export LOG_DIR="{work:path}"
          cd {artifacts:decompressedPath}/awsggpi4/awsggpi4 && exec {work:path}/venv/bin/python -u objectdetection.py
        Setenv:
          PYTHONUNBUFFERED: '1'
